# Generated by Django 3.2.4 on 2021-06-24 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='Аббревиатура')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('number', models.CharField(max_length=15, verbose_name='Группа')),
                ('field_of_study', models.CharField(max_length=120, verbose_name='Направление')),
                ('profile_of_study', models.CharField(max_length=150, verbose_name='Профиль/Направленность')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rating.faculties', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Почта')),
                ('first_name', models.CharField(max_length=140, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=140, verbose_name='Отчество')),
                ('type_user', models.CharField(choices=[('Студент', 'Студент'), ('Преподаватель', 'Преподаватель'), ('Сотрудник деканата', 'Сотрудник деканата')], max_length=20)),
                ('number_zachetka', models.CharField(blank=True, max_length=50, verbose_name='Номер зачетки')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rating.faculties', verbose_name='Факультет')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rating.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Statements',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('date', models.DateTimeField(verbose_name='Дата экзамена/зачета')),
                ('control', models.CharField(choices=[('Экзамен', 'Экзамен'), ('Зачёт', 'Зачёт'), ('Зачёт c оценкой', 'Зачёт c оценкой')], max_length=20, verbose_name='Экзамен/зачет')),
                ('disciplines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.disciplines', verbose_name='Дисциплина')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rating.users', verbose_name='ФИО преподавателя')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
            },
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('mark', models.CharField(choices=[('2', 'неуд'), ('3', 'удовл'), ('4', 'хор'), ('5', 'отл'), ('зач', 'зач'), ('незач', 'незач'), ('незач(2)', 'незач(неуд)'), ('зач(3)', 'зач(удовл)'), ('зач(4)', 'зач(хор)'), ('зач(5)', 'зач(отл)')], max_length=12, verbose_name='Оценка')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.statements', verbose_name='Ведомость')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.users', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AddField(
            model_name='disciplines',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.faculties', verbose_name='Факультет'),
        ),
    ]
