# Generated by Django 3.2.4 on 2021-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='BMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='CHEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='GEOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='HIST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='IMIT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='INYAZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='ISN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='LAU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='MIEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Physicists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='PI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='PSY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='SAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='SR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('book', models.FileField(upload_to='media')),
            ],
        ),
    ]
